version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Password12345!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - bankapp-network
    volumes:
      - sqlvolume:/var/opt/mssql
   

  bankapp:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081" 
    depends_on:
      - sqlserver
    networks:
      - bankapp-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: on-failure

networks:
  bankapp-network:

volumes:
  sqlvolume:
